# Generated by Django 3.2.7 on 2021-10-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
