# Generated by Django 3.2.7 on 2021-10-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='users_that_like',
            field=models.ManyToManyField(related_name='liked_articles', related_query_name='like_article', to='app.User'),
        ),
    ]
