# Generated by Django 3.2.7 on 2021-10-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_article_users_that_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='users_that_like',
            field=models.ManyToManyField(related_name='liked_articles', related_query_name='liked_article', to='app.User'),
        ),
    ]
